### ISSUE TITLE
Error trying to build genome index (using test files)

### ISSUE THREAD

**Issue by c5creative** [indrops/indrops#17]
Greetings,

I am trying to reproduce the test example. I have installed all of the required tools/packages.

As per the README, I am running the first step in generating the genome index (after downloading exactly the files described).
```
# This command will go through all the steps for creating the index
python indrops.py project.yaml build_index \
    --genome-fasta-gz DOWNLOAD_DIR/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz \
    --ensembl-gtf-gz DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.gtf.gz
```
Also, my project.yaml file contains (in part) the relevant info:
```
paths : 
  bowtie_index : "/PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated"
```
Here is the complete output of the above:
```
Filtering GTF
Filtered GTF contains 180471 transcripts (41569 genes)
   - ignored 17180 transcripts from 14622 pseudogenes)
   - ignored 351 read-through transcripts (112 genes)
Gunzipping Genome
rsem-extract-reference-transcripts /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated 0 /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.gtf None 0 /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
Parsed 200000 lines
Parsed 400000 lines
Parsed 600000 lines
Parsed 800000 lines
Parsed 1000000 lines
Parsed 1200000 lines
Parsed 1400000 lines
Parsed 1600000 lines
Parsed 1800000 lines
Parsed 2000000 lines
Parsed 2200000 lines
Parsed 2400000 lines
Parsing gtf File is done!
/PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa is processed!
180471 transcripts are extracted.
Extracting sequences is done!
Group File is generated!
Transcript Information File is generated!
Chromosome List File is generated!
Extracted Sequences File is generated!

rsem-preref /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.transcripts.fa 0 /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated -l 5
Refs.makeRefs finished!
Refs.saveRefs finished!
/PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.idx.fa is generated!
/PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.n2g.idx.fa is generated!

bowtie-build -f /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.n2g.idx.fa /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated
Traceback (most recent call last):
  File "/PATH_TO/bin/bcbio-data/anaconda/lib/python2.7/encodings/__init__.py", line 157, in <module>
    codecs.register(search_function)
AttributeError: 'module' object has no attribute 'register'
"bowtie-build -f /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated.n2g.idx.fa /PATH_TO/bin/indrops/test/DOWNLOAD_DIR/Homo_sapiens.GRCh38.85.annotated" failed! Plase check if you provide correct parameters/options for the pipeline!
Traceback (most recent call last):
  File "/PATH_TO/bin/indrops/indrops.py", line 1775, in <module>
    project.build_transcriptome(args.genome_fasta_gz, args.ensembl_gtf_gz, mode=args.mode)
  File "/PATH_TO/bin/indrops/indrops.py", line 522, in build_transcriptome
    raise Exception(" Error in rsem-prepare reference ")
Exception:  Error in rsem-prepare reference 
```
So, it looks like its dying in the ``bowtie-build`` routine. Any ideas what the problem could be?

Thanks,
JP

**Comment by c5creative** [comment]
Looks like there was an incompatibility with the bcbio bowtie version. Appears to be working now.
