### ISSUE TITLE
KeyError: 'library_prefix' for v3

### ISSUE THREAD

**Issue by allumette** [indrops/indrops#26]
Hello,
  Recently I got an error for v3 data: I set "fastq_path: '{library_prefix}_{read}.fastq.gz'" in yaml as the instruction said, and got the error as following:

Traceback (most recent call last):
  File "indrops-master/indrops.py", line 1692, in <module>
    project = IndropsProject(args.project)
  File "indrops-master/indrops.py", line 278, in __init__
    input_filename = os.path.join(run['dir'], run['fastq_path'].format(split_affix=affix, read='{read}'))
KeyError: 'library_prefix'

I think source code:
input_filename = os.path.join(run['dir'], run['fastq_path'].format(split_affix=affix, read='{read}'))
should have "library_prefix=lib['library_prefix']" in format, like v1 and v2.

If "{library_prefix}" is not supported, I want to know the correct setting for the following data,:
lib1_R1.fastq.gz
lib1_R2.fastq.gz
lib1_R3.fastq.gz
lib1_R4.fastq.gz
lib2_R1.fastq.gz
lib2_R2.fastq.gz
lib2_R3.fastq.gz
lib2_R4.fastq.gz

**Comment by jpcartailler** [comment]
Seems like it would be easy enough to try your approach, i.e. adding the `library_prefix=lib['library_prefix']` as a parameter to the `os.path.join()` call... I don't have a V3 library to try, unfortunately.
