### ISSUE TITLE
how to build index for cdna?

### ISSUE THREAD

**Issue by allumette** [indrops/indrops#27]
Hello,
  I can build index for Mus_musculus.GRCm38.dna_sm.toplevel.fa, but when build for Mus_musculus.GRCm38.cdna.all.fa, there is a bug:

"rsem-extract-reference-transcripts Mus_musculus.GRCm38.cdna.all.fa 0 Mus_musculus.GRCm38.cdna.all.fa.gtf None 0 Mus_musculus.GRCm38.cdna.all" failed! Plase check if you provide correct parameters/options for the pipeline!
Traceback (most recent call last):
  File "../indrops.py", line 1770, in <module>
    project.build_transcriptome(args.genome_fasta_gz, args.ensembl_gtf_gz, mode=args.mode)
  File "../indrops.py", line 522, in build_transcriptome
    raise Exception(" Error in rsem-prepare reference ")
Exception:  Error in rsem-prepare reference

It seems some message missing in fa file when RSEM working, is there a way to build index for cdna?

**Comment by Peshkin** [comment]
have this ever been resolved ?
