### ISSUE TITLE
Quantify step hangs

### ISSUE THREAD

**Issue by pcantalupo** [indrops/indrops#30]
Hello,
I'm running Indrops on Linux. It runs successfully through the filter, identify_abundant_barcodes, and sort steps. However, it is hanging forever on the quantify step. Here is an example:

```
python /ihome/crc/install/indrops/indrops/indrops.py indrops.yaml quantify --min-reads 4000
[BKVm5] This worker assigned 6930 out of 6930 total barcodes.
Library       Barcode  Reads   Counts  Ambigs
BKVm5         bcEZOU
```
It hanged for at least 24 hours before I cancelled it. Here is the output I see after cancelling:

```
^CTraceback (most recent call last):
  File "/ihome/crc/install/indrops/indrops/indrops.py", line 1759, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "/ihome/crc/install/indrops/indrops/indrops.py", line 841, in quantify_expression
    min_counts = min_counts, run_filter=run_filter)
  File "/ihome/crc/install/indrops/indrops/indrops.py", line 933, in quantify_expression_for_barcode
    p1.stdin.write(line)
KeyboardInterrupt
```

Please recommend what I should try next.

Thank you

**Comment by atrostle** [comment]
Hello,

Were you able to fix this?

**Comment by pcantalupo** [comment]
No. I had to run Indrops on a Mac and then when I ran into Issue #31 I copied files to the Linux machine it was able to finish the processing.

**Comment by atrostle** [comment]
Bizarre, would you mind sharing your project.yaml file that this worked with on mac?

Thanks

**Comment by pcantalupo** [comment]
Here are both yaml files. 
[mac.yaml.txt](https://github.com/indrops/indrops/files/3044291/mac.yaml.txt)
[linux.yaml.txt](https://github.com/indrops/indrops/files/3044292/linux.yaml.txt)

**Comment by atrostle** [comment]
Thank you!

**Comment by atrostle** [comment]
I fixed this issue with https://github.com/indrops/indrops/issues/18#issuecomment-430044303 

Seems like I had an error in my initial use of conda, and the way the quantification step after bowtie alignment calls python made it hang.
