### ISSUE TITLE
argument list too long error during BAM merging

### ISSUE THREAD

**Issue by pcantalupo** [indrops/indrops#31]
I'm working on a MacOSX High Sierra system. When Indrops gets to the BAM merging step, I get this error:

```
$ bash scripts/slurm.indrops.quantifyOnly.job
[BKVm5] This worker assigned 6247 out of 6247 total barcodes.
    6247 previously quantified, 0 previously ignored, 0 left for this run.
Library       Barcode  Reads   Counts  Ambigs    
Per barcode quantification completed.
Merging BAM output.
Traceback (most recent call last):
  File "/Users/foo/local/opt/indrops/indrops.py", line 1759, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "/Users/foo/local/opt/indrops/indrops.py", line 859, in quantify_expression
    subprocess.check_output([self.project.paths.samtools, 'merge', '-f', merged_bam_filename]+genomic_bams, stderr=subprocess.STDOUT)
  File "/Users/foo/local/opt/miniconda2/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/foo/local/opt/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/foo/local/opt/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

I tried to set a high ulimit with `ulimit -n 20000` before starting my script but this failed too. Not sure what to try next. Thank you

**Comment by piloter2** [comment]
ulimit -n 1000000
ulimit -s 8192000
