### ISSUE TITLE
calling yaml.load() without Loader=... is deprecated; EOFError

### ISSUE THREAD

**Issue by radio1988** [indrops/indrops#33]
Dear Developer, 

I got the following error when I was running identify_abundant_barcodes:

```
 ${myPython} $indrops $yaml identify_abundant_barcodes

/project/xxx/scRNAseq/tools/indrops/indrops.py:200: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.yaml = yaml.load(project_yaml_file_handle)
Traceback (most recent call last):
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 1747, in <module>
    project.libraries[library].identify_abundant_barcodes()
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 581, in identify_abundant_barcodes
    for k, v in self.barcode_counts.items():
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 560, in barcode_counts
    for k, v in part.part_barcode_counts.items():
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 1139, in part_barcode_counts
    self._part_barcode_counts = pickle.load(f)
EOFError
```

I had no problem running the previous filter step:
```
# Code
${myPython} ${indrops} $yaml filter --total-workers ${N1} --worker-index $i

# report
Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
source ~/scRNAseq.profile; i=-1; which python; python /project/xxx/scRNAseq/tools/indrops/indrops.py rui_analysis.yaml filter --total-workers 4 --worker-index 1
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   3149.45 sec.
    Max Memory :                                 2617 MB
    Average Memory :                             2563.76 MB
    Total Requested Memory :                     8000.00 MB
    Delta Memory :                               5383.00 MB
    Max Swap :                                   -
    Max Processes :                              38
    Max Threads :                                169
    Run time :                                   2385 sec.
    Turnaround time :                            2387 sec.

The output (if any) is above this job summary.

# tail of stdout
 Total Reads                 Valid Reads  No index    No BC1    No BC2    No UMI   |  kit-t2-d10  kit-t2-d30  kit-t2t3-d  kit-t2-d30  kit-ctrl-d  kit-ctrl-d  kit-t2t3-d  kit-t2t3-d  kit-t2-d10  kit-ctrl-d
   111000000     23.7 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.4%        9.8%       14.6%       14.6%       11.8%        7.9%
   112000000     23.7 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.4%        9.8%       14.6%       14.6%       11.8%        7.9%
   113000000     23.6 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.4%        9.8%       14.6%       14.6%       11.8%        7.9%
   114000000     23.6 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.5%        9.8%       14.6%       14.6%       11.8%        7.9%
   115000000     23.7 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.5%        9.8%       14.6%       14.6%       11.9%        7.9%
   115386339      0.0 sec/M        83.7%      2.1%     11.3%      2.9%      0.0%   |        7.3%        8.9%        8.9%        9.7%        6.5%        9.8%       14.6%       14.6%       11.9%        7.9%

------------------------------------------------------------
Sender: LSF System <lsfadmin@c37b04>
Subject: Job 8597632[1]: <flt[1-4]> in cluster <umghpcc> Done
```

Variables and versions
```
module load bcl2fastq/1.8.4 bowtie/1.2.2 jdk/1.8.0_171 RSEM/1.3.0 samtools/1.3
source activate py27
indrops=/project/xxx/scRNAseq/tools/indrops/indrops.py
myPython=python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44)
```

I changed line 200 of indrops.py, 
from `self.yaml = yaml.load(project_yaml_file_handle)` 
to  `self.yaml = yaml.load(project_yaml_file_handle, Loader=yaml.FullLoader)`

The error message becomes:
```
${myPython} $indrops $yaml identify_abundant_barcodes
Traceback (most recent call last):
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 1747, in <module>
    project.libraries[library].identify_abundant_barcodes()
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 581, in identify_abundant_barcodes
    for k, v in self.barcode_counts.items():
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 560, in barcode_counts
    for k, v in part.part_barcode_counts.items():
  File "/project/xxx/scRNAseq/tools/indrops/indrops.py", line 1139, in part_barcode_counts
    self._part_barcode_counts = pickle.load(f)
EOFError
```

What was the problem? How can I make identify_abundant_barcodes running?

Thanks!
Ray

**Comment by radio1988** [comment]
I’ve found the problem in my LSF submission code:
--worker-index \$((\$LSB_JOBINDEX-1))  # works
i=\$((\$LSB_JOBINDEX-1));  --worker-index $i # fails
This behavior is unexpected for me, I’ll keep that in mind.
