### ISSUE TITLE
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ab9b2f04280> ignored

### ISSUE THREAD

**Issue by radio1988** [indrops/indrops#36]
Hello!

I was using the low level pipeline to process the indrop scRNAseq data. I had two successful experiences with two different datasets. However, this time I got a new dataset from HMS and it gave me the following errors. I tested my pipeline with previous dataset, it worked well again. Can you help us troubleshoot what the problem is? 

Thanks!

```
Filtering run "1910_scRNAseq", library "N/A", part "L004"
path/indrops.py:300: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  paths = yaml.load(f)['paths']
path/indrops.py:325: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._parameters = yaml.load(f)['parameters']
Filtering 1910_scRNAseq, file ./n/files/Genetics/BPF-NGS/nextseq/191030_NB501715_0501_AHHYFNBGXC/Data/Intensities/BaseCalls/Undetermined_S0_L004_{read}_001.fastq.gz
 Total Reads                 Valid Reads  No index    No BC1    No BC2    No UMI   |  E2F4_W3_64  G2F4_K2_11  G2F4_W2_64  G2F4_K3_11  R_W2_39  S5_W3_6  G2F4_K1_64 R_K2_39  S5_W1_5  R_K1_39  S5_K2_5  R_W1_39  S5_K3_6  S5_W2_5  R_K3_65  G2F4_W1_64  R_W3_65  S5_K1_5  G2F4_W4_11
Traceback (most recent call last):
  File "path/indrops.py", line 1743, in <module>
    part.filter_and_count_reads()
  File "path/indrops.py", line 1634, in filter_and_count_reads
    trim_processes[lib_index].write(to_fastq_lines(bc, umi, bio_read, bio_qual, r_name[1:]))
IOError: [Errno 32] Broken pipe
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b00a0> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0730> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8acbe0> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8acb90> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8acaa0> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0a00> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8ace60> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc7ab5a0> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc79c280> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0190> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0370> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0460> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0910> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0550> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0280> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8acf50> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8acd70> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity_filter_process at 0x2ac3cc8b0820> ignored
Exception OSError: OSError(16, 'Device or resource busy') in <generator object trimmomatic_and_low_complexity
_filter_process at 0x2ac3cc8b0640> ignored
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002b78d802dede, pid=64941, tid=0x00002b78d76f8b20
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x929ede]#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002b0061a35ede, pid=65309, tid=0x00002b0061100b20
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x929ede]#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002b2a7f0d5ede, pid=65439, tid=0x00002b2a7e7a0b20
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x929ede]#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002ad5c8515ede, pid=1275, tid=0x00002ad5c7be0b20
```

**Comment by prabal97** [comment]
Hi, I am getting a same error while running the filter command 
`indrops.py:200: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.yaml = yaml.load(project_yaml_file_handle)
Filtering run "Run4", library "N/A", part "1"
indrops.py:300: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  paths = yaml.load(f)['paths']
indrops.py:110: DeprecationWarning: 'U' mode is deprecated
  with open(barcode_file, 'rU') as f:
indrops.py:325: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._parameters = yaml.load(f)['parameters']
Filtering Run4, file /mnt/hwstor9k_data1/prabal/retts_syndrome/gedata/test/SRR7145420_1.fastq.gz
Traceback (most recent call last):
  File "indrops.py", line 1520, in _weave_fastqs
    names = [next(s)[:-1].split()[0] for s in streams]
  File "indrops.py", line 1520, in <listcomp>
    names = [next(s)[:-1].split()[0] for s in streams]
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "indrops.py", line 1743, in <module>
    part.filter_and_count_reads()
  File "indrops.py", line 1621, in filter_and_count_reads
    for r_name, seqs, quals in self._weave_fastqs(input_fastqs):
RuntimeError: generator raised StopIteration
Exception ignored in: <generator object LibrarySequencingPart.trimmomatic_and_low_complexity_filter_process at 0x7fbe3bf20e50>
Traceback (most recent call last):
  File "indrops.py", line 1270, in trimmomatic_and_low_complexity_filter_process
    p1.wait()
  File "indrops.py", line 188, in __exit__
    shutil.rmtree(self.tmpdir)
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000002b50280700000033'
Exception ignored in: <generator object LibrarySequencingPart.trimmomatic_and_low_complexity_filter_process at 0x7fbe3ba97850>
Traceback (most recent call last):
  File "indrops.py", line 1270, in trimmomatic_and_low_complexity_filter_process
    p1.wait()
  File "indrops.py", line 188, in __exit__
    shutil.rmtree(self.tmpdir)
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/mnt/hwstor9k_data1/prabal/temp/anaconda/envs/retts/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: `'.nfs000000002b50300700000034'``

**Comment by ld32** [comment]
I figured it out. It is a bug in python script:
trim_polyA_and_filter_low_complexity_reads.py

The bug is triggered by reads like:
name: GTACGGAC-TCCAGGGA:TCCTAT:A00794_411_HWC3YDRXX_1_1101_5159_1000
seq:GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
qual:FFFFFFFFFFFFF,F:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

I fixed it. You can find the modification:
https://github.com/ld32/indrops/commit/1dd5efd4237fce1f5543e0d542805dd8aeb8e22e

You can download a new copy of the the script, replace the older file, then run:
https://github.com/ld32/indrops/blob/master/trim_polyA_and_filter_low_complexity_reads.py

You can also directly download the whole package and replace the old one.
https://github.com/ld32/indrops

The error message was buried inside the python pipe, which confused us to believe there issue was with the pipe.
