### ISSUE TITLE
quantification step stops

### ISSUE THREAD

**Issue by sunliang3361** [indrops/indrops#40]
Hi, the quantification steps stops after processing 2000+ barcodes. If I re-run the script, it will process more barcodes (maybe another 300+ barcodes), and then it stops again. Can anyone tell me what my problem is ? Thanks.
The error code is below:

sample1       bcBENR   1041    144     0         
sample1       bcFAEK   1042    265     0         
sample1       bcHJXG   1040    253     0         
sample1       bcCNXC   1040    198     0         
sample1       bcBTAY   1039    199     0         
sample1       bcCUPC   1039    257     0         
sample1       bcGAPY   1038    171     0         
Traceback (most recent call last):
  File "../indrops/indrops.py", line 1759, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "../indrops/indrops.py", line 841, in quantify_expression
    min_counts = min_counts, run_filter=run_filter)
  File "../indrops/indrops.py", line 970, in quantify_expression_for_barcode
    subprocess.check_output([self.project.paths.samtools, 'sort', '-o', sorted_bam, genomic_bam], stderr=subprocess.STDOUT)
  File "/programs/x86_64-linux/python/2.7.15/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/programs/x86_64-linux/python/2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/programs/x86_64-linux/python/2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  Concatenating output from all workers.
  GZIPping concatenated output.
Aggregation completed in scRNA_project/sample1/sample1.counts.tsv.gz
Traceback (most recent call last):
  File "../indrops/indrops.py", line 1767, in <module>
    project.libraries[library].aggregate_counts(analysis_prefix=args.analysis_prefix)
  File "../indrops/indrops.py", line 1004, in aggregate_counts
    total_workers = list(total_workers)[0]
IndexError: list index out of range

**Comment by ibrenckle** [comment]
Hi Liang,
Are you running this on O2, or an O2-like slurm system where you are splitting tasks between workers?
Best,
Ian
________________________________

**Comment by sunliang3361** [comment]
Hi Ian, 
I am running it on E2 Slurm system which is very similar to O2. I only use one node! Thank you 

Liang
