### ISSUE TITLE
samtools merge error

### ISSUE THREAD

**Issue by sunliang3361** [indrops/indrops#41]
I got the following error message when indrops tried to merge all bam files together. Any ideas what my problems are? Too may cells? Thank you.

[sample1] This worker assigned 3941 out of 3941 total barcodes.
    3941 previously quantified, 0 previously ignored, 0 left for this run.
Library       Barcode  Reads   Counts  Ambigs    
Per barcode quantification completed.
Merging BAM output.
   CMD: ['samtools', 'merge', '-f', 'scRNA_project/sample1/quant_dir/worker0_1.bam', 'scRNA_project/sample1/quant_dir/bcAKQD.genomic.sorted.bam', 'scRNA_project/sample1/quant_dir/bcCWGX.genomic.sorted.bam', 'scRNA_project/sample1/quant_dir/bcDKZH.genomic.sorted.bam', 'scRNA_project/sample1/quant_dir/bcABNV.genomic.sorted.bam', 'scRNA_project/sample1/quant_dir/bcCAWC.genomic.sorted.bam', 'scRNA_project/sam
   stdout/stderr:
[E::hts_open_format] Failed to open file "scRNA_project/sample1/quant_dir/bcIKBG.genomic.sorted.bam" : Too many open files
samtools merge: fail to open "scRNA_project/sample1/quant_dir/bcIKBG.genomic.sorted.bam": Too many open files

Traceback (most recent call last):
  File "../indrops/indrops.py", line 1759, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "../indrops/indrops.py", line 864, in quantify_expression
    raise Exception(" === Error in samtools merge === ")
Exception:  === Error in samtools merge ===

**Comment by piloter2** [comment]
Could you enter "ulimit -n 8192" ?
