### ISSUE TITLE
Issue running example sample runs

### ISSUE THREAD

**Issue by SaraD08** [indrops/indrops#44]
Running the following filter command yielded the following errors (yml file pasted below and I have full permissions to the project file and that path is correct in the yaml file:
python ../indrops.py indrops.yaml filter --total-workers 18

../indrops.py:200: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.yaml = yaml.load(project_yaml_file_handle)
Filtering run "Run3_test", library "test_lib1", part "L001"
../indrops.py:300: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  paths = yaml.load(f)['paths']
../indrops.py:325: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._parameters = yaml.load(f)['parameters']
Traceback (most recent call last):
  File "../indrops.py", line 1743, in <module>
    part.filter_and_count_reads()
  File "../indrops.py", line 1325, in filter_and_count_reads
    with self.trimmomatic_and_low_complexity_filter_process() as trim_process:
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "../indrops.py", line 1248, in trimmomatic_and_low_complexity_filter_process
    p2 = subprocess.Popen(low_complexity_filter_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

----Yaml:

project_name : "test"
project_dir : "/efs/analysis/Platform/indrops_test/"
sequencing_runs : 
  - name : "Run3_test"
    version : 'v2'
    dir : "/efs/analysis/software/indrops/test/seq_runs/run_v2_split/"
    fastq_path : "{library_prefix}_{split_affix}_{read}_001.fastq.gz"
    split_affixes : ["L001", "L002"]
    libraries : 
      - {library_name: "test_lib1", library_prefix: "lib1"}
      - {library_name: "test_lib2", library_prefix: "lib2"}

paths : 
  bowtie_index : "/efs/analysis/software/indrops/test/test_ref/"
  python_dir : "/usr/bin/python2"
  samtools_dir : "/usr/local/bin/samtools/"
  rsem_dir : "/efs/analysis/software/RSEM-1.3.3/"
  java_dir : "/usr/bin/java"
parameters : # OPTIONAL PARAMETERS
#   umi_quantification_arguments:
#     m : 10 #Ignore reads with more than M alignments, after filtering on distance from transcript end.
#     u : 1 #Ignore counts from UMI that should be split among more than U genes.
#     d : 600 #Maximal distance from transcript end, NOT INCLUDING THE POLYA TAIL
#     split-ambigs: False #If umi is assigned to m genes, add 1/m to each gene's count (instead of 1)
#     min_non_polyA: 15 #Require reads to align to this much non-polyA sequence. (Set to 0 to disable filtering on this parameter.)
#   output_arguments:
#     output_unaligned_reads_to_other_fastq: False
#     low_complexity_mask: False
#   bowtie_arguments:
#     m : 200
#     n : 1
#     l : 15
#     e : 1000
  trimmomatic_arguments:
    LEADING: "28"
    SLIDINGWINDOW: "4:20"
    MINLEN: "16"

Thank you for your time and help with getting started with running indrops.

**Comment by SaraD08** [comment]
Providing an update with using the full path for the command still doesn't work but I have 2 library folders in the project directory but the fastq files are empty:
python /efs/analysis/software/indrops/indrops_test.py /efs/analysis/software/indrops/test/indrops.yaml filter --total-workers 18
/efs/analysis/software/indrops/indrops_test.py:200: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.yaml = yaml.load(project_yaml_file_handle)
<__main__.IndropsProject instance at 0x7fdd4861d7e8>
[<__main__.V1V2Filtering instance at 0x7fdd4864fb90>, <__main__.V1V2Filtering instance at 0x7fdd4864fbd8>, <__main__.V1V2Filtering instance at 0x7fdd4864fa28>, <__main__.V1V2Filtering instance at 0x7fdd4864fa70>]
Filtering run "Run3_test", library "test_lib1", part "L001"
/efs/analysis/software/indrops/indrops_test.py:300: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  paths = yaml.load(f)['paths']
/efs/analysis/software/indrops/indrops_test.py:325: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._parameters = yaml.load(f)['parameters']
Traceback (most recent call last):
  File "/efs/analysis/software/indrops/indrops_test.py", line 1745, in <module>
    part.filter_and_count_reads()
  File "/efs/analysis/software/indrops/indrops_test.py", line 1325, in filter_and_count_reads
    with self.trimmomatic_and_low_complexity_filter_process() as trim_process:
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/efs/analysis/software/indrops/indrops_test.py", line 1248, in trimmomatic_and_low_complexity_filter_process
    p2 = subprocess.Popen(low_complexity_filter_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/efs/home/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory

**Comment by akbock** [comment]
I am having what looks like an identical problem running the filter command! Were you/was anyone able to determine what was happening in this case? (I'm happy to provide more information on my setup as well!)

**Comment by akbock** [comment]
I know this is older, but I had the same issue recently and came across this thread so responding in case it helps anyone else! I  was able to solve this problem by deleting from the project YAML file the paths to the Python, RSEM, Samtools, and Java directories, since I was running the code in a conda environment constructed as described in Appendix 2-3. I did keep the paths to the bowtie index (which started out as an empty folder that the .ebwt files were deposited in automatically) and bowtie.
