### ISSUE TITLE
No such file or directory: 'test/test_project/test_lib0/quant_dir/worker0_1.metrics.tsv'

### ISSUE THREAD

**Issue by pcantalupo** [indrops/indrops#6]
Hello,
I'm running indrops with the test data. I am able to run analysis steps 0, 1, 2, and 3. But when trying to run Step 4 Quantify, I get this error:

```
$ python indrops.py test/test_project.yaml quantify
[test_lib0] This worker assigned 0 out of 0 total barcodes.
Library       Barcode  Reads   Counts  Ambigs
Per barcode quantification completed.
Traceback (most recent call last):
  File "indrops.py", line 1724, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "indrops.py", line 827, in quantify_expression
    with open(metrics_output_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'test/test_project/test_lib0/quant_dir/worker0_1.metrics.tsv'
```

What can I do to fix this error? Thank you

**Comment by pcantalupo** [comment]
Determined that the test data does not have enough abundant barcodes to allow quantification. Closing issue.
