### ISSUE TITLE
broken pipe for quantify mode

### ISSUE THREAD

**Issue by d3str4d0** [indrops/indrops#7]
Hi,

I was wondering if you could help me out here. I did the following (working w/ SGE):

 qsub -N quant_sc -j y -o quant.log -cwd -b y -l h_vmem=16G -pe smp 4 'python indrops.py my.yaml quantify'

...and I get the following error:

Traceback (most recent call last):
  File "indrops.py", line 1730, in <module>
    no_bam=args.no_bam, run_filter=target_runs)
  File "indrops.py", line 822, in quantify_expression
    min_counts = min_counts, run_filter=run_filter)
  File "indrops.py", line 913, in quantify_expression_for_barcode
    p1.stdin.write(line)
IOError: [Errno 32] Broken pipe

So far I went through your protocol step by step, doing the filtering, the retrieval of abundant barcodes as well as the sorting w/o major troubles. Any guesses from your side?

Help would be much appreciated.

Best,

**Comment by nachocab** [comment]
I got the same error

**Comment by fkokocinski** [comment]
The broken pipe message originates from a Python bug described here where a subprocess fails early: https://bugs.python.org/issue10963
The actual cause of the failed subprocess might be Bowtie crashing. Have a look if your genome index path is correct and if you can run the Bowtie step separately.

**Comment by francescarivello** [comment]
Hi! Also get exactly the same error. How did you manage to fix it?

Best,

**Comment by fkokocinski** [comment]
Double-check the "bowtie_index" and "bowtie_dir" path in your config and maybe in the log/output.
If that is correct insert something like
```
print_to_stderr(bowtie_cmd)
print_to_stderr(quant_cmd)
```
at line 926 (before the `p1 = subprocess.Popen` call) in indrops.py to show the actual command it is trying to run. You can then run this command on the command line to check for errors.

**Comment by leighnd** [comment]
It could be that you are specifying the location of your bowtie_index, but not adding the name of the index generated. For example, your index named "indrops_index", which should be prepended an all your index files (i.e. ebwt, transcripts.fa, etc.) may be in 

`path/to/bowtie/index/`

but if you put 

`path/to/bowtie/index/`

in your .yaml file you'll get the above noted broken pipe error. You should specify instead

`path/to/bowtie/index/indrops_index`

**Comment by francescarivello** [comment]
@leighnd I am actually adding the name of the index generated in the .yaml file, so that should not constitute the problem.

**Comment by piloter2** [comment]
Maybe your fastq.gz file was broken.
